[tool.poetry]
name = "shifty"
version = "0.1.0"
description = ""
authors = ["Andreas Eismann <a.eismann@senbax.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
reflex = "^0.6.2.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
